services:
  backend:
    image: daniilleschev/umtracker-backend:latest
    env_file: .env
    expose:
      - "8000"
    restart: always
    networks:
      - um_net

  frontend:
    image: daniilleschev/umtracker-frontend:latest
    ports:
      - "8080:80"
    restart: always
    networks:
      - um_net

networks:
  um_net: